### ISSUE TITLE
About  "contentloc"

### ISSUE THREAD

**Issue by ghost** [swesust/backEnd#3]
What is the use of  "contentloc"?

**Comment by rafiulgits** [comment]
![issue](https://user-images.githubusercontent.com/27845214/50723927-d870db80-110e-11e9-924c-e880005745cd.png)

to manage this kinds of information. 
if we use a .JSON file to handle those information about the user, the user can add more contents without creating new col in database.
just like:
Programming Language: C, C++
Course Projects: ******
Github Projects: ************
ACM problem solution:
**
**
whatever.
Everything will store in a .JSON file. 
### **contentloc actually carry this json file location**

@12tonoy

**Comment by rafiulgits** [comment]
```json
{
	"bio" : "hellllllo",
	"interest" : ["X", "Y", "Z"],
	"programming language" : ["C", "Python", "Java"],
	"skill" : ["android", "django"],
	"projects" : ["https://github.com/rafiulgits/IP_Messenger", "https://github.com/sakkhat/p250"],
	"codeforces" : "user name",
	"uhunt id" : "user id",
	"vjudge" : "user name"
}
```

I thing this  keys are enough now to carry content information about a user.


`bio : string`
`interest : list`
`programming language : list`
`skill : list`
`projects : list`
`codeforces : string`
`uhunt : number`
`vjudge : string`

**Comment by rafiulgits** [comment]
@12tonoy
